name: sni_app
description: Applicazione ufficiale Skull Network Italia
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

# ================= SPLASH SCREEN =================
flutter_native_splash:
  color: "#000000"
  image: assets/images/sni_logo.png

  android_12:
    image: assets/images/sni_logo.png
    color: "#000000"

# ================= FLUTTER =================
flutter:
  uses-material-design: true

  assets:
    - assets/images/sni_logo.png

# ================= APP ICON =================
flutter_icons:
  android: true
  ios: false
  image_path: assets/images/sni_logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/sni_logo.png
